version: "2"
services:
  radotp:
   image: ghcr.io/abbas-gheydi/radotp:2.0.1
   restart: always
   ports:
    - "80:8080"
    - "443:8081"
    - "1812:1812/udp"
   volumes:
   - ./config/:/etc/radotp/
   depends_on:
   - db
   - prometheus

  prometheus:
   image: prom/prometheus:v2.47.0
   restart: always
   volumes:
   - prom_data:/prometheus-data
   - type: bind
     source: ./prometheus.yml
     target: /etc/prometheus/prometheus.yml

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

volumes:
  db_data:
  prom_data:
  pgadmin: